import React, { useState, useEffect, useRef, useCallback } from 'react';
import { Send, Loader2, Scale, Filter, BookOpen, ExternalLink, Sparkles, RefreshCw, Search, Copy, Check, Upload, Network } from 'lucide-react';
import { Badge } from './ui/badge';
import { ScrollArea } from './ui/scroll-area';
import { toast } from 'sonner';
import ComplianceBulkUploadModal from './ComplianceBulkUploadModal';
import ComplianceGraph3D from './ComplianceGraph3D';

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const SOURCES = [
  { id: 'nse', label: 'NSE', color: 'text-sky-400', dot: 'bg-sky-500' },
  { id: 'bse', label: 'BSE', color: 'text-amber-400', dot: 'bg-amber-500' },
  { id: 'sebi', label: 'SEBI', color: 'text-emerald-400', dot: 'bg-emerald-500' },
];
const YEARS = (() => {
  const arr = [];
  const cur = new Date().getFullYear();
  for (let y = cur; y >= 2010; y--) arr.push(y);
  return arr;
})();

const SUGGESTED = [
  'What are the latest SEBI insider trading disclosure rules?',
  'Recent circulars on ESG reporting requirements for listed companies',
  'How have listing obligations (LODR) evolved since 2015?',
  'NSE circulars on algorithmic trading risk management',
  'BSE circulars on corporate governance norms',
];

// Build a publication-ready markdown report: question + answer (citations remapped
// to sequential [1][2]… in order of first appearance) + numbered bibliography.
const buildReportMarkdown = (question, answer, citations = []) => {
  const firstIndexOf = new Map();
  const order = [];
  const re = /\[CIT-(\d+)\]/g;
  let m;
  while ((m = re.exec(answer)) !== null) {
    const id = `CIT-${m[1]}`;
    if (!firstIndexOf.has(id)) {
      firstIndexOf.set(id, order.length + 1);
      order.push(id);
    }
  }
  // Include any cited sources that weren't inline (still relevant context)
  citations.forEach(c => {
    if (!firstIndexOf.has(c.id)) {
      firstIndexOf.set(c.id, order.length + 1);
      order.push(c.id);
    }
  });

  // Replace [CIT-N] → [n]
  const remappedAnswer = answer
    .replace(/\[CIT-(\d+)\]/g, (_, n) => {
      const id = `CIT-${n}`;
      const idx = firstIndexOf.get(id);
      return idx ? `[${idx}]` : `[CIT-${n}]`;
    })
    // Strip the auto-generated "## Sources" block at the bottom (we rebuild it)
    .replace(/\n#{1,3}\s*Sources[\s\S]*$/i, '')
    .trim();

  const sortedCits = [...citations].sort(
    (a, b) => (firstIndexOf.get(a.id) || 999) - (firstIndexOf.get(b.id) || 999)
  );
  const bibliography = sortedCits.map(c => {
    const idx = firstIndexOf.get(c.id);
    const url = c.url ? ` — ${c.url}` : '';
    return `[${idx}] **${c.source}** · ${c.circular_no} · ${c.date} — *${c.title}* (${c.category})${url}`;
  }).join('\n');

  const ts = new Date().toLocaleString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });

  return `# Compliance Research — ${ts} IST

**Question:** ${question}

---

${remappedAnswer}

---

## References

${bibliography || '_No sources cited._'}

_Generated by BMIA Compliance Research · Powered by Claude Sonnet 4.5 on NSE/BSE/SEBI circulars._
`;
};

// Render markdown-lite content (bold, headings, lists, [CIT-N] chips)
const renderMarkdown = (text, citations = []) => {
  if (!text) return null;
  const citeById = Object.fromEntries(citations.map(c => [c.id, c]));

  const renderInline = (line) => {
    // Replace [CIT-N] with chip
    const parts = [];
    let last = 0;
    const re = /\[CIT-(\d+)\]/g;
    let m;
    let k = 0;
    while ((m = re.exec(line)) !== null) {
      if (m.index > last) parts.push(<span key={`t-${k++}`}>{line.slice(last, m.index)}</span>);
      const id = `CIT-${m[1]}`;
      const cit = citeById[id];
      parts.push(
        <span
          key={`c-${k++}`}
          title={cit ? `${cit.source} | ${cit.circular_no} | ${cit.date}` : id}
          className="inline-flex items-center gap-1 px-1.5 py-0.5 mx-0.5 rounded bg-[hsl(var(--primary))]/15 text-[hsl(var(--primary))] text-[10px] font-semibold border border-[hsl(var(--primary))]/30 hover:bg-[hsl(var(--primary))]/25 cursor-pointer align-middle"
          data-testid={`citation-chip-${id}`}
        >
          {id}
        </span>
      );
      last = m.index + m[0].length;
    }
    if (last < line.length) parts.push(<span key={`t-${k++}`}>{line.slice(last)}</span>);
    // Bold
    return parts.map((p, i) => {
      if (typeof p.props?.children !== 'string') return p;
      const s = p.props.children;
      if (!s.includes('**')) return p;
      const subs = s.split(/(\*\*[^*]+\*\*)/g).map((part, j) =>
        part.startsWith('**') && part.endsWith('**')
          ? <strong key={j} className="text-[hsl(var(--foreground))]">{part.slice(2, -2)}</strong>
          : <React.Fragment key={j}>{part}</React.Fragment>
      );
      return <span key={i}>{subs}</span>;
    });
  };

  return text.split('\n').map((line, i) => {
    const trimmed = line.trim();
    if (trimmed.startsWith('## ')) {
      return <h3 key={i} className="text-sm font-bold text-[hsl(var(--primary))] mt-3 mb-1">{trimmed.slice(3)}</h3>;
    }
    if (trimmed.startsWith('# ')) {
      return <h2 key={i} className="text-base font-bold text-[hsl(var(--foreground))] mt-3 mb-1">{trimmed.slice(2)}</h2>;
    }
    if (trimmed.startsWith('- ') || trimmed.startsWith('• ')) {
      return <li key={i} className="text-sm text-[hsl(var(--foreground))] ml-4 mb-0.5 list-disc">{renderInline(trimmed.slice(2))}</li>;
    }
    if (trimmed === '') return <div key={i} className="h-2" />;
    return <p key={i} className="text-sm text-[hsl(var(--foreground))] leading-relaxed mb-1">{renderInline(line)}</p>;
  });
};

function CopyReportButton({ question, answer, citations, testId }) {
  const [copied, setCopied] = React.useState(false);
  const handleCopy = async () => {
    try {
      const md = buildReportMarkdown(question, answer, citations);
      await navigator.clipboard.writeText(md);
      setCopied(true);
      toast.success('Report copied to clipboard', {
        description: 'Paste into an email, PDF, or document — citations are numbered [1][2]… with a full bibliography.',
      });
      setTimeout(() => setCopied(false), 2500);
    } catch (e) {
      toast.error('Could not copy to clipboard');
    }
  };
  return (
    <button
      onClick={handleCopy}
      data-testid={testId}
      title="Copy this answer + numbered citations as markdown"
      className="ml-auto flex items-center gap-1 px-2 py-0.5 rounded-md text-[10px] font-semibold bg-[hsl(var(--surface-2))] hover:bg-[hsl(var(--surface-3))] text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))] border border-[hsl(var(--border))]"
      style={{ transition: 'background-color 0.15s ease' }}
    >
      {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
      {copied ? 'Copied' : 'Cite in report'}
    </button>
  );
}

export default function ComplianceResearchPanel({ compact = false }) {
  const [question, setQuestion] = useState('');
  const [selectedSources, setSelectedSources] = useState(['nse', 'bse', 'sebi']);
  const [yearFilter, setYearFilter] = useState('');
  const [messages, setMessages] = useState([]);
  const [loading, setLoading] = useState(false);
  const [stats, setStats] = useState(null);
  const endRef = useRef(null);

  const loadStats = useCallback(() => {
    fetch(`${BACKEND_URL}/api/compliance/stats`)
      .then(r => r.json())
      .then(setStats)
      .catch(() => {});
  }, []);

  useEffect(() => { loadStats(); }, [loadStats]);

  // Auto-poll stats: 10s while any source is backfilling, 60s when all live
  useEffect(() => {
    const isBackfilling = stats?.overall_phase === 'backfill';
    const interval = setInterval(loadStats, isBackfilling ? 10000 : 60000);
    return () => clearInterval(interval);
  }, [stats?.overall_phase, loadStats]);

  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, loading]);

  const toggleSource = (id) => {
    setSelectedSources(prev =>
      prev.includes(id) ? (prev.length > 1 ? prev.filter(s => s !== id) : prev) : [...prev, id]
    );
  };

  const ask = async (q) => {
    const text = (q ?? question).trim();
    if (!text || loading) return;
    setMessages(prev => [...prev, { role: 'user', content: text }]);
    setQuestion('');
    setLoading(true);
    try {
      const body = { question: text, sources: selectedSources, top_k: 10 };
      if (yearFilter) body.year_filter = parseInt(yearFilter, 10);
      const res = await fetch(`${BACKEND_URL}/api/compliance/research`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      setMessages(prev => [...prev, {
        role: 'assistant',
        content: data.answer || 'No response',
        citations: data.citations || [],
        sources_searched: data.sources_searched || [],
        error: data.error,
      }]);
    } catch (e) {
      setMessages(prev => [...prev, { role: 'assistant', content: `Error: ${e.message}`, citations: [] }]);
    }
    setLoading(false);
  };

  const [syncing, setSyncing] = useState(false);

  const triggerIngest = async () => {
    if (syncing) return;
    setSyncing(true);
    // stats.stores is a dict keyed by source name: { nse: {...}, bse: {...}, sebi: {...} }
    const storesObj = (stats && stats.stores && typeof stats.stores === 'object') ? stats.stores : {};
    const baseline = {};
    let totBefore = 0;
    for (const [src, s] of Object.entries(storesObj)) {
      const circ = (s && s.circular_count) || 0;
      baseline[src] = { circ, chunks: (s && s.chunk_count) || 0 };
      totBefore += circ;
    }

    toast.loading('Sync started — fetching latest NSE / BSE / SEBI circulars', { id: 'force-sync' });

    try {
      const r = await fetch(`${BACKEND_URL}/api/compliance/ingest-now`, { method: 'POST' });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);

      let attempts = 0;
      const maxAttempts = 30;  // 30 × 3s = 90s
      const poll = async () => {
        attempts += 1;
        try {
          const res = await fetch(`${BACKEND_URL}/api/compliance/stats`);
          const s = await res.json();
          setStats(s);
          const obj = (s && s.stores && typeof s.stores === 'object') ? s.stores : {};
          const changes = [];
          let totAfter = 0;
          for (const [src, st] of Object.entries(obj)) {
            const circ = (st && st.circular_count) || 0;
            totAfter += circ;
            const b = baseline[src] || { circ: 0 };
            if (circ > b.circ) changes.push({ src, delta: circ - b.circ });
          }
          if (changes.length > 0) {
            const by = changes.map(c => `${c.src.toUpperCase()}: +${c.delta}`).join(' · ');
            const delta = totAfter - totBefore;
            toast.success(`Sync complete — ${delta} new circular${delta === 1 ? '' : 's'}`, {
              id: 'force-sync', description: by, duration: 6000,
            });
            setSyncing(false);
            return;
          }
          if (attempts >= maxAttempts) {
            toast.info('No new circulars found', {
              id: 'force-sync',
              description: 'Upstream regulators have no updates since the last ingest.',
              duration: 6000,
            });
            setSyncing(false);
            return;
          }
          setTimeout(poll, 3000);
        } catch {
          setTimeout(poll, 3000);
        }
      };
      setTimeout(poll, 2500);
    } catch (err) {
      toast.error('Force sync failed', {
        id: 'force-sync', description: String(err?.message || err), duration: 6000,
      });
      setSyncing(false);
    }
  };

  // Mobile: hide the filters pane by default and show a toggle button
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [bulkUploadOpen, setBulkUploadOpen] = useState(false);

  // ── GraphRAG 3D viewer state ──
  const [graphOpen, setGraphOpen] = useState(false);
  const [graphLoading, setGraphLoading] = useState(false);
  const [graphData, setGraphData] = useState(null);
  const [graphTitle, setGraphTitle] = useState('3D Compliance Graph');

  const openGraphForMessage = async (msgIdx) => {
    const msg = messages[msgIdx];
    const userQ = messages[msgIdx - 1]?.content || '';
    if (!msg || !userQ) return;
    setGraphTitle(userQ.length > 80 ? userQ.slice(0, 80) + '…' : userQ);
    setGraphData(null);
    setGraphLoading(true);
    setGraphOpen(true);
    try {
      const res = await fetch(`${BACKEND_URL}/api/compliance/graph/query`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          question: userQ,
          sources: selectedSources,
          top_k: 12,
          enrich: true,
        }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      setGraphData(data.subgraph || { nodes: [], edges: [] });
    } catch (e) {
      toast.error('Could not build graph', { description: String(e?.message || e) });
      setGraphData({ nodes: [], edges: [] });
    } finally {
      setGraphLoading(false);
    }
  };

  return (
    <div className={`flex flex-col sm:flex-row ${compact ? 'h-full' : 'h-[calc(100vh-3.5rem)] sm:h-[calc(100vh-3.5rem)]'} bg-[hsl(var(--background))]`} data-testid="compliance-panel">
      {/* Mobile: filters toggle bar */}
      <div className="sm:hidden flex items-center justify-between px-3 py-2 border-b border-[hsl(var(--border))] bg-[hsl(var(--surface-1))]">
        <button
          onClick={() => setFiltersOpen(v => !v)}
          className="flex items-center gap-1.5 text-xs font-medium text-[hsl(var(--foreground))] px-3 py-1.5 rounded-md bg-[hsl(var(--surface-2))] border border-[hsl(var(--border))]"
          data-testid="compliance-filters-toggle"
        >
          <Filter className="w-3.5 h-3.5" />
          {filtersOpen ? 'Hide' : 'Sources & status'}
        </button>
        {stats?.overall_phase && (
          <span className={`text-[9px] font-semibold px-1.5 py-0.5 rounded uppercase tracking-wider ${
            stats.overall_phase === 'live'
              ? 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/30'
              : 'bg-amber-500/15 text-amber-400 border border-amber-500/30'
          }`}>{stats.overall_phase}</span>
        )}
      </div>
      {/* LEFT: Filters + Stats */}
      <div className={`${filtersOpen ? 'flex' : 'hidden'} sm:flex ${compact ? 'w-full sm:w-60' : 'w-full sm:w-72'} border-b sm:border-b-0 sm:border-r border-[hsl(var(--border))] bg-[hsl(var(--surface-1))] flex-col flex-shrink-0 max-h-[60vh] sm:max-h-none overflow-y-auto`}>
        <div className="p-4 border-b border-[hsl(var(--border))]">
          <div className="flex items-center gap-2 mb-1">
            <Scale className="w-4 h-4 text-[hsl(var(--primary))]" />
            <h2 className="text-sm font-display font-semibold tracking-wide">Compliance Research</h2>
          </div>
          <p className="text-[11px] text-[hsl(var(--muted-foreground))]">NSE · BSE · SEBI circulars · 2010 → today</p>
        </div>

        <div className="p-4 space-y-4 overflow-y-auto">
          {/* Sources */}
          <div>
            <div className="flex items-center gap-1.5 text-[11px] font-semibold text-[hsl(var(--muted-foreground))] uppercase tracking-wider mb-2">
              <Filter className="w-3 h-3" /> Sources
            </div>
            <div className="space-y-1">
              {SOURCES.map(src => {
                const s = stats?.stores?.[src.id];
                const active = selectedSources.includes(src.id);
                return (
                  <button
                    key={src.id}
                    onClick={() => toggleSource(src.id)}
                    data-testid={`source-toggle-${src.id}`}
                    className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-xs font-medium border ${
                      active
                        ? 'bg-[hsl(var(--surface-3))] border-[hsl(var(--primary))]/40 text-[hsl(var(--foreground))]'
                        : 'bg-[hsl(var(--surface-2))] border-transparent text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]'
                    }`}
                    style={{ transition: 'background-color 0.15s ease' }}
                  >
                    <span className="flex items-center gap-2">
                      <span className={`w-2 h-2 rounded-full ${src.dot}`} />
                      <span className={active ? src.color : ''}>{src.label}</span>
                    </span>
                    <span className="text-[10px] text-[hsl(var(--muted-foreground))]">
                      {s?.ready ? `${s.chunk_count}` : s?.circular_count || 0}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Year Filter */}
          <div>
            <div className="text-[11px] font-semibold text-[hsl(var(--muted-foreground))] uppercase tracking-wider mb-2">Year</div>
            <select
              value={yearFilter}
              onChange={(e) => setYearFilter(e.target.value)}
              data-testid="year-filter-select"
              className="w-full px-3 py-2 rounded-lg text-xs bg-[hsl(var(--surface-2))] border border-[hsl(var(--border))] text-[hsl(var(--foreground))]"
            >
              <option value="">All years</option>
              {YEARS.map(y => <option key={y} value={y}>{y}</option>)}
            </select>
          </div>

          {/* Ingestion Progress */}
          <div className="pt-3 border-t border-[hsl(var(--border))]">
            <div className="flex items-center justify-between mb-2">
              <div className="text-[11px] font-semibold text-[hsl(var(--muted-foreground))] uppercase tracking-wider">Ingestion</div>
              {stats?.overall_phase && (
                <span
                  data-testid="overall-phase-badge"
                  className={`text-[9px] font-semibold px-1.5 py-0.5 rounded uppercase tracking-wider ${
                    stats.overall_phase === 'live'
                      ? 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/30'
                      : stats.overall_phase === 'backfill'
                      ? 'bg-amber-500/15 text-amber-400 border border-amber-500/30'
                      : 'bg-[hsl(var(--surface-3))] text-[hsl(var(--muted-foreground))]'
                  }`}
                >
                  {stats.overall_phase === 'backfill' && (
                    <span className="inline-block w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse mr-1 align-middle" />
                  )}
                  {stats.overall_phase === 'live' && (
                    <span className="inline-block w-1.5 h-1.5 rounded-full bg-emerald-400 mr-1 align-middle" />
                  )}
                  {stats.overall_phase}
                </span>
              )}
            </div>

            <div className="space-y-2" data-testid="progress-source-list">
              {SOURCES.map(src => {
                const s = stats?.stores?.[src.id];
                if (!s) return null;
                const pct = Math.max(2, s.progress_pct || 0); // min 2% so bar is visible
                return (
                  <div key={src.id} className="space-y-1" data-testid={`progress-${src.id}`}>
                    <div className="flex items-center justify-between text-[11px]">
                      <div className="flex items-center gap-1.5">
                        <span className={`w-1.5 h-1.5 rounded-full ${src.dot}`} />
                        <span className={src.color}>{src.label}</span>
                        {s.phase === 'backfill' && (
                          <span className="text-[9px] text-amber-400 uppercase font-semibold">Backfilling</span>
                        )}
                        {s.phase === 'live' && (
                          <span className="text-[9px] text-emerald-400 uppercase font-semibold">Live</span>
                        )}
                      </div>
                      <span className="font-mono text-[hsl(var(--foreground))]">{(s.progress_pct || 0).toFixed(0)}%</span>
                    </div>
                    <div className="h-1.5 rounded-full bg-[hsl(var(--surface-2))] overflow-hidden">
                      <div
                        className={`h-full ${s.phase === 'live' ? 'bg-emerald-500' : 'bg-amber-500'}`}
                        style={{ width: `${pct}%`, transition: 'width 0.5s ease-out' }}
                      />
                    </div>
                    <div className="flex items-center justify-between text-[9px] text-[hsl(var(--muted-foreground))]">
                      <span>{s.years_covered}/{s.total_years_span} yrs · {(s.circular_count || 0).toLocaleString()} docs</span>
                      {s.oldest_date && <span className="font-mono">→ {s.oldest_date.slice(0, 7)}</span>}
                    </div>
                    {s.last_error && s.circular_count === 0 && (
                      <div className="text-[9px] text-red-400/80 leading-tight" data-testid={`error-${src.id}`}>
                        ⚠ {s.last_error.slice(0, 80)}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

            {stats?.totals && (
              <div className="mt-3 pt-2 border-t border-[hsl(var(--border))] text-[10px] text-[hsl(var(--muted-foreground))] space-y-0.5">
                <div className="flex justify-between">
                  <span>Total circulars</span>
                  <span className="font-mono text-[hsl(var(--foreground))]">{stats.totals.circulars.toLocaleString()}</span>
                </div>
                <div className="flex justify-between">
                  <span>Vector chunks</span>
                  <span className="font-mono text-[hsl(var(--foreground))]">{stats.totals.chunks.toLocaleString()}</span>
                </div>
                <div className="flex justify-between">
                  <span>Overall</span>
                  <span className="font-mono text-[hsl(var(--foreground))]">{(stats.totals.avg_progress_pct || 0).toFixed(0)}%</span>
                </div>
              </div>
            )}

            <button
              onClick={triggerIngest}
              disabled={syncing}
              data-testid="trigger-ingest-btn"
              className="mt-3 w-full flex items-center justify-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-medium bg-[hsl(var(--surface-2))] hover:bg-[hsl(var(--surface-3))] text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))] border border-[hsl(var(--border))] disabled:opacity-60 disabled:cursor-wait"
              style={{ transition: 'background-color 0.15s ease' }}
            >
              <RefreshCw className={`w-3 h-3 ${syncing ? 'animate-spin' : ''}`} />
              {syncing ? 'Syncing...' : 'Force sync now'}
            </button>

            <button
              onClick={() => setBulkUploadOpen(true)}
              data-testid="open-bulk-upload-btn"
              title="Upload a ZIP archive of historical circulars (bypasses upstream rate limits)"
              className="mt-2 w-full flex items-center justify-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] font-medium bg-[hsl(var(--primary))]/10 hover:bg-[hsl(var(--primary))]/20 text-[hsl(var(--primary))] border border-[hsl(var(--primary))]/30"
              style={{ transition: 'background-color 0.15s ease' }}
            >
              <Upload className="w-3 h-3" />
              Bulk upload archive
            </button>
          </div>

          {messages.length === 0 && (
            <div className="pt-3 border-t border-[hsl(var(--border))]">
              <div className="text-[11px] font-semibold text-[hsl(var(--muted-foreground))] uppercase tracking-wider mb-2 flex items-center gap-1">
                <Sparkles className="w-3 h-3" /> Try asking
              </div>
              <div className="space-y-1.5">
                {SUGGESTED.map((s, i) => (
                  <button
                    key={i}
                    onClick={() => ask(s)}
                    data-testid={`suggested-q-${i}`}
                    className="w-full text-left px-2.5 py-2 rounded-md text-[11px] bg-[hsl(var(--surface-2))] hover:bg-[hsl(var(--surface-3))] text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))] border border-[hsl(var(--border))] leading-snug"
                    style={{ transition: 'background-color 0.15s ease' }}
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* RIGHT: Chat */}
      <div className="flex-1 flex flex-col min-w-0">
        <ScrollArea className="flex-1">
          <div className="max-w-3xl mx-auto px-6 py-6 space-y-6">
            {messages.length === 0 && (
              <div className="text-center py-16" data-testid="compliance-empty-state">
                <div className="inline-flex w-12 h-12 rounded-full bg-[hsl(var(--primary))]/10 items-center justify-center mb-3">
                  <BookOpen className="w-6 h-6 text-[hsl(var(--primary))]" />
                </div>
                <h3 className="text-lg font-display font-semibold mb-2">Research Indian market regulations</h3>
                <p className="text-sm text-[hsl(var(--muted-foreground))] max-w-md mx-auto leading-relaxed">
                  Ask any question about NSE, BSE, or SEBI circulars. Every claim comes with an inline citation traceable to the source circular. Powered by Claude Sonnet 4.5.
                </p>
              </div>
            )}

            {messages.map((m, i) => (
              <div key={i} className={m.role === 'user' ? 'flex justify-end' : ''} data-testid={`msg-${m.role}-${i}`}>
                {m.role === 'user' ? (
                  <div className="max-w-[80%] px-4 py-2.5 rounded-2xl bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] text-sm">
                    {m.content}
                  </div>
                ) : (
                  <div>
                    <div className="flex items-center gap-2 mb-2 text-[11px] text-[hsl(var(--muted-foreground))]">
                      <Scale className="w-3.5 h-3.5 text-[hsl(var(--primary))]" />
                      <span className="font-semibold text-[hsl(var(--foreground))]">Compliance AI</span>
                      {m.sources_searched?.length > 0 && (
                        <span className="flex items-center gap-1">
                          · searched {m.sources_searched.map(s => s.toUpperCase()).join(', ')}
                        </span>
                      )}
                      {m.citations?.length > 0 && !m.error && (
                        <>
                          <button
                            onClick={() => openGraphForMessage(i)}
                            data-testid={`view-graph-${i}`}
                            title="Visualise the citations and their related regulations in a 3D knowledge graph"
                            className="ml-auto flex items-center gap-1 px-2 py-0.5 rounded-md text-[10px] font-semibold bg-[hsl(var(--primary))]/15 hover:bg-[hsl(var(--primary))]/25 text-[hsl(var(--primary))] border border-[hsl(var(--primary))]/30"
                            style={{ transition: 'background-color 0.15s ease' }}
                          >
                            <Network className="w-3 h-3" />
                            View 3D Graph
                          </button>
                          <CopyReportButton
                            question={messages[i - 1]?.content || ''}
                            answer={m.content}
                            citations={m.citations || []}
                            testId={`copy-report-${i}`}
                          />
                        </>
                      )}
                    </div>
                    <div className="prose prose-invert prose-sm max-w-none text-[hsl(var(--foreground))]">
                      {renderMarkdown(m.content, m.citations || [])}
                    </div>
                    {m.citations?.length > 0 && (
                      <div className="mt-4 pt-3 border-t border-[hsl(var(--border))]">
                        <div className="text-[11px] font-semibold text-[hsl(var(--muted-foreground))] uppercase tracking-wider mb-2">
                          Sources ({m.citations.length})
                        </div>
                        <div className="space-y-1.5">
                          {m.citations.map((c) => (
                            <a
                              key={c.id}
                              href={c.url || '#'}
                              target="_blank"
                              rel="noopener noreferrer"
                              onClick={(e) => { if (!c.url) e.preventDefault(); }}
                              data-testid={`citation-${c.id}`}
                              className="flex items-start gap-2 px-3 py-2 rounded-lg bg-[hsl(var(--surface-2))] hover:bg-[hsl(var(--surface-3))] border border-[hsl(var(--border))] text-xs"
                              style={{ transition: 'background-color 0.15s ease' }}
                            >
                              <Badge variant="outline" className="text-[9px] px-1.5 py-0 mt-0.5 shrink-0">{c.id}</Badge>
                              <div className="flex-1 min-w-0">
                                <div className="text-[hsl(var(--foreground))] truncate font-medium">{c.title}</div>
                                <div className="text-[10px] text-[hsl(var(--muted-foreground))] mt-0.5">
                                  {c.source} · {c.circular_no} · {c.date} · {c.category}
                                </div>
                              </div>
                              {c.url && <ExternalLink className="w-3 h-3 text-[hsl(var(--muted-foreground))] shrink-0 mt-1" />}
                            </a>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))}

            {loading && (
              <div className="flex items-center gap-2 text-sm text-[hsl(var(--muted-foreground))]" data-testid="compliance-loading">
                <Loader2 className="w-4 h-4 animate-spin text-[hsl(var(--primary))]" />
                Researching circulars...
              </div>
            )}
            <div ref={endRef} />
          </div>
        </ScrollArea>

        {/* Input */}
        <div className="border-t border-[hsl(var(--border))] bg-[hsl(var(--surface-1))] p-4">
          <div className="max-w-3xl mx-auto flex items-end gap-2">
            <div className="flex-1 relative">
              <Search className="w-4 h-4 absolute left-3 top-3 text-[hsl(var(--muted-foreground))]" />
              <textarea
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    ask();
                  }
                }}
                placeholder="Ask about any NSE, BSE, or SEBI regulation..."
                rows={1}
                data-testid="compliance-question-input"
                className="w-full pl-10 pr-4 py-2.5 rounded-xl text-sm bg-[hsl(var(--surface-2))] border border-[hsl(var(--border))] text-[hsl(var(--foreground))] placeholder:text-[hsl(var(--muted-foreground))] resize-none focus:outline-none focus:ring-1 focus:ring-[hsl(var(--primary))]"
              />
            </div>
            <button
              onClick={() => ask()}
              disabled={!question.trim() || loading}
              data-testid="compliance-send-btn"
              className="h-11 px-4 rounded-xl bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] text-sm font-medium flex items-center gap-2 disabled:opacity-40 disabled:cursor-not-allowed hover:opacity-90"
              style={{ transition: 'opacity 0.15s ease' }}
            >
              {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
              Ask
            </button>
          </div>
        </div>
      </div>

      <ComplianceBulkUploadModal
        open={bulkUploadOpen}
        onClose={() => setBulkUploadOpen(false)}
        onCompleted={loadStats}
      />

      <ComplianceGraph3D
        open={graphOpen}
        onClose={() => setGraphOpen(false)}
        subgraph={graphData}
        loading={graphLoading}
        title={graphTitle}
      />
    </div>
  );
}
